KeyMap = ->
  @moveBackward = 83
  @moveForward = 87
  @moveLeft = 65
  @moveRight = 68
  @moveDown = 17
  @moveDownAlt = 88
  @moveUp = 16
  @moveUpAlt = 32
  @arrowLeft = 37
  @arrowUp = 38
  @arrowRight = 39
  @arrowDown = 40
  @modifyPlayerSpeed = 69
  @changeMovement = 81
  @saveWorld = 80
  @usePrevBlock = 78
  @useNextBlock = 77
  @useNextBlockData = 66
  @useCodeEditor = 71
  @executeJavaScript = 72
  @clearStorage = 73
  @changeCamera = 86
  @reloadBlockConfig = 75

window.keyMap = new KeyMap
